### ISSUE TITLE
Please publish with PyPi

### ISSUE THREAD

**Issue by JohnHind** [CedarGroveStudios/CircuitPython_NAU7802#4]
Please could you publish this in PyPi so it can be installed, with dependencies, using PIP3?
Ref: [https://forums.adafruit.com/viewtopic.php?p=971026#p971026](https://forums.adafruit.com/viewtopic.php?p=971026#p971026)

**Comment by CedarGroveStudios** [comment]
Thank you very much for your suggestion. At this time, Cedar Grove Studios is not planning to extend support to PyPi as Adafruit has agreed to incorporate the driver into their CircuitPython ecosystem at some point: https://github.com/adafruit/Adafruit_NAU7802/issues/2

**Comment by ladyada** [comment]
@CedarGroveStudios do you want to transfer the repo or should we fork?

**Comment by CedarGroveStudios** [comment]
A fork would probably be best since I’ll need to retain the version that supports the dual channel capability of my custom FeatherWing.

**Comment by JohnHind** [comment]
@ladyada OK, many thanks! I'll be very happy if I can install it as-is with dependencies using PIP3 with a discoverable library name and find the documentation in the usual place!

**Comment by CedarGroveStudios** [comment]
> > @ladyada A fork would probably be best since I’ll need to retain the version that supports the dual channel capability of my custom FeatherWing.
> 
> On second thought, I’ll just create a local copy of the existing repo and will transfer the existing.

... except GitHub won't allow the transfer to an organization where I don't have the capability to create a repo.

**Comment by ladyada** [comment]
iiiinteresting, can you try to transfer it to me?

**Comment by ladyada** [comment]
perf - i xfered it to https://github.com/adafruit/CircuitPython_NAU7802

**Comment by CedarGroveStudios** [comment]
Excellent. I apologize for the inconvenience caused by this fire drill.

**Comment by JohnHind** [comment]
Still not getting a PIP install on this guys!
```
 pip install adafruit-circuitpython-NAU7802
ERROR: Could not find a version that satisfies the requirement adafruit-circuitpython-NAU7802 (from versions: none)
ERROR: No matching distribution found for adafruit-circuitpython-NAU7802
 pip install circuitpython-NAU7802
ERROR: Could not find a version that satisfies the requirement circuitpython-NAU7802 (from versions: none)
ERROR: No matching distribution found for circuitpython-NAU7802
 pip install NAU7802
ERROR: Could not find a version that satisfies the requirement NAU7802 (from versions: none)
ERROR: No matching distribution found for NAU7802
 pip install cedargrove-circuitpython-NAU7802
ERROR: Could not find a version that satisfies the requirement cedargrove-circuitpython-NAU7802 (from versions: none)
ERROR: No matching distribution found for cedargrove-circuitpython-NAU7802
 pip install CedarGrove-circuitpython-NAU7802
ERROR: Could not find a version that satisfies the requirement CedarGrove-circuitpython-NAU7802 (from versions: none)
ERROR: No matching distribution found for CedarGrove-circuitpython-NAU7802
 pip install CedarGrove-CircuitPython-NAU7802
ERROR: Could not find a version that satisfies the requirement CedarGrove-CircuitPython-NAU7802 (from versions: none)
ERROR: No matching distribution found for CedarGrove-CircuitPython-NAU7802
```

**Comment by JohnHind** [comment]
Ah, Sorry, should be:
```
pip3 install cedargrove-nau7802
```
Sod's law strikes again!
